### ISSUE TITLE
Doesn't work with Android M

### ISSUE THREAD

**Issue by agrieve** [openstf/STFService.apk#2]
First error I hit was:

```
FTL/device 29607 [0599cc54] Setup had an error Error: At least one of these paths should exist: /home/agrieve/.nvm/versions/node/v0.12.7/lib/node_modules/stf/vendor/minicap/shared/android-6.0/armeabi-v7a/minicap.so, /home/agrieve/.nvm/versions/node/v0.12.7/lib/node_modules/stf/vendor/minicap/shared/android-23/armeabi-v7a/minicap.so, /home/agrieve/.nvm
/versions/node/v0.12.7/lib/node_modules/stf/vendor/minicap/shared/android-6.0/armeabi/minicap.so, /home/agrieve/.nvm/versions/node/v0.12.7/lib/node_modules/stf/vendor/minicap/shared/android-23/armeabi/minicap.so
```

Copying `/home/agrieve/.nvm/versions/node/v0.12.7/lib/node_modules/stf/vendor/minicap/shared/android-M` -> `/home/agrieve/.nvm/versions/node/v0.12.7/lib/node_modules/stf/vendor/minicap/shared/android-23` got me farther:

`stf local` now shows:

```
FTL/device 29949 [0599cc54] Setup had an error TimeoutError: operation timed out
    at afterTimeout (/usr/local/google/home/agrieve/.nvm/versions/node/v0.12.7/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
    at timeoutTimeout (/usr/local/google/home/agrieve/.nvm/versions/node/v0.12.7/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout (timers.js:119:15)
FTL/util:lifecycle 29949 [0599cc54] Shutting down due to fatal error
```

A logcat on the devices shows:

```
09-23 14:19:57.102  8860  8860 D AndroidRuntime: Calling main entry jp.co.cyberagent.stf.Agent
09-23 14:19:57.105  8860  8860 D AndroidRuntime: Shutting down VM
09-23 14:19:58.176  8874  8874 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
09-23 14:19:58.182  8874  8874 D AndroidRuntime: CheckJNI is OFF
09-23 14:19:58.233  8874  8874 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
09-23 14:19:58.291  8874  8874 I Radio-JNI: register_android_hardware_Radio DONE
09-23 14:19:58.327  8874  8874 D AndroidRuntime: Calling main entry jp.co.cyberagent.stf.Agent
09-23 14:19:58.334  8874  8874 D AndroidRuntime: Shutting down VM
09-23 14:19:58.335  8874  8874 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
09-23 14:19:58.335  8874  8874 E AndroidRuntime: java.lang.UnsupportedOperationException: UserActivityWakeInjector is not supported
09-23 14:19:58.335  8874  8874 E AndroidRuntime:        at jp.co.cyberagent.stf.compat.PowerManagerWrapper$UserActivityWakeInjector.<init>(PowerManagerWrapper.java:81)
09-23 14:19:58.335  8874  8874 E AndroidRuntime:        at jp.co.cyberagent.stf.compat.PowerManagerWrapper.<init>(PowerManagerWrapper.java:22)
09-23 14:19:58.335  8874  8874 E AndroidRuntime:        at jp.co.cyberagent.stf.Agent.run(Agent.java:101)
09-23 14:19:58.335  8874  8874 E AndroidRuntime:        at jp.co.cyberagent.stf.Agent.main(Agent.java:51)
09-23 14:19:58.335  8874  8874 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
09-23 14:19:58.335  8874  8874 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
09-23 14:19:58.336  8874  8874 E AndroidRuntime: Error reporting crash
09-23 14:19:58.336  8874  8874 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:503)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:55)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2606)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2605)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:34)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:84)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
09-23 14:19:58.336  8874  8874 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
09-23 14:19:58.336  8874  8874 I Process : Sending signal. PID: 8874 SIG: 9
```

**Comment by sorccu** [comment]
Which Android image are you using?

**Comment by agrieve** [comment]
The Nexus 6 image from https://developer.android.com/preview/download.html

**Comment by sorccu** [comment]
This should now be fixed. The latest openstf/stf master has also been updated, although there is no new release yet.
