### ISSUE TITLE
service Exception : java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by pinotao** [openstf/STFService.apk#23]
run stf on an device then occurs an exception in stf-service：
`
E/AndroidRuntime(23484): FATAL EXCEPTION: main
E/AndroidRuntime(23484): Process: jp.co.cyberagent.stf, PID: 23484
E/AndroidRuntime(23484): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in jp.co.cyberagent.stf.monitor.ConnectivityMonitor$1@2cc7d830
E/AndroidRuntime(23484): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:769)
E/AndroidRuntime(23484): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(23484): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(23484): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(23484): 	at android.app.ActivityThread.main(ActivityThread.java:5016)
E/AndroidRuntime(23484): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23484): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(23484): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
E/AndroidRuntime(23484): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
E/AndroidRuntime(23484): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(23484): Caused by: java.lang.UnsupportedOperationException
E/AndroidRuntime(23484): 	at jp.co.cyberagent.stf.proto.Wire$ConnectivityEvent.dynamicMethod(Wire.java:4180)
E/AndroidRuntime(23484): 	at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:332)
E/AndroidRuntime(23484): 	at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:1457)
E/AndroidRuntime(23484): 	at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:254)
E/AndroidRuntime(23484): 	at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:419)
E/AndroidRuntime(23484): 	at jp.co.cyberagent.stf.monitor.ConnectivityMonitor.peek(ConnectivityMonitor.java:77)
E/AndroidRuntime(23484): 	at jp.co.cyberagent.stf.monitor.AbstractMonitor.peek(AbstractMonitor.java:17)
E/AndroidRuntime(23484): 	at jp.co.cyberagent.stf.monitor.ConnectivityMonitor$1.onReceive(ConnectivityMonitor.java:30)
E/AndroidRuntime(23484): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:759)
E/AndroidRuntime(23484): 	... 9 more
E/cutils-trace(23509): Error opening trace file: No such file or directory (2)
`

**Comment by sorccu** [comment]
Run:

adb devices -l

And

adb shell getprop | grep ro.product

And post output of both for that device.

**Comment by pinotao** [comment]
adb devices -l
`
74c2d3a6-e301-4eb8-9f58-65e21159d486 device usb:14134000 product:autolink_6dl model:M60_MX6DL device:autolink_6dl
`
adb shell getprop | grep ro.product

`
adb -s 74c2d3a6-e301-4eb8-9f58-65e21159d486 shell getprop | grep ro.product
[ro.product.board]: [AUTOLINK]
[ro.product.brand]: [Freescale]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.device]: [autolink_6dl]
[ro.product.locale.language]: [zh]
[ro.product.locale.region]: [CN]
[ro.product.manufacturer]: [Freescale]
[ro.product.model]: [M60-MX6DL]
[ro.product.name]: [autolink_6dl]
`

**Comment by sorccu** [comment]
It’s ungooglable. No idea what kind of a device we’re talking about.
